site_name: PyCharm IDE Documentation

repo_name: mikkosio/User-Doc
repo_url: https://github.com/mikkosio/User-Doc

nav:
  - Home: "index.md"
  - Creating Your First Project: "pages/first-project.md"
  - Debugging Your Code: "pages/debugging.md"
  - Creating a Github Repository: "pages/creating-repo.md"
  - Glossary: "pages/glossary.md"

theme:
  name: material

  features:
    - toc.integrate 
    - navigation.footer
    - content.code.copy

  font:
    text: Roboto
    code: Roboto Mono

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    logo: logo

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets



