site_name: PyCharm IDE Documentation

nav:
  - Home: "introduction.md"
  - Getting Started: "pages/first-project.md"

theme:
  name: material

  features:
  - toc.integrate 

  font:
    text: Roboto
    code: Roboto Mono

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    logo: logo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
